service:        janus
image: hackclub/janus

builder:
  arch: amd64

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
servers:
  web:
    - 192.168.0.1

proxy:
  ssl: true

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f

volumes:
  - "janus_storage:/rails/storage"

asset_path: /rails/public/assets
